# pdp_ins_gen.py

import os
import sys
import math
import pandas as pd
from pysat.formula import IDPool

class PDP_reform:
    def __init__(self, pdpName, num_reqs, num_vehs, capacity, knn=3, increment=None):
        self.registry = increment
        self.varID = 0

        self.pdpName = pdpName
        self.num_reqs = int(num_reqs)
        self.num_vehs = int(num_vehs)
        self.capacity = int(capacity)
        self.knn = int(knn)

        self.adjMatrx = []
        self.coordinates = []
        self.locaList = []
        self.requestList = []
        self.vehicleList = []
        
        self.lenOfCoord = 0
        self.lenOfLocation = 0
        self.lenOfRequest = 0
        self.lenOfVehicle = 0
        
        self.id2Var = None

        self.coordCSV = f'2DNode_{self.pdpName}.csv'
        self.reqstCSV = f'requestInfo{self.num_reqs}_{self.pdpName}.csv'
        self.adjMxCSV = f'adjMatrx{self.knn}_{self.pdpName}.csv'
        
        # Load the dynamic vehicle configuration generated by pdp_ins_arg.py
        self.vehicleCSV = f'vehicleInfo{self.num_vehs}_{self.pdpName}.csv'
        
        self.readCSV()

        # ==================== Core Variable Allocation ====================
        
        # 1. x: Topology network mapping (Shared)
        self.xVarList = [[[0] * (1 + self.lenOfLocation)
                          for j in range(1 + self.lenOfLocation)]
                          for i in range(self.lenOfVehicle)]
        
        # 2. y: Mandatory request assignment (Shared)
        self.yVarList = [[0] * self.lenOfVehicle for i in range(self.lenOfRequest)]
        
        # 3. nu: Order-encoding for MaxSAT (MTZ sub-tour elimination and precedence)
        self.nuVarList = [[[0] * self.lenOfLocation 
                          for j in range(self.lenOfLocation)]
                          for i in range(self.lenOfVehicle)]
                          
        # 4. u: Integer MTZ variables for MIP
        self.uVarList = [[0] * self.lenOfLocation for i in range(self.lenOfVehicle)]
        
        # 5. h: Capacity tracking variables for MIP
        self.hVarList = [[0] * (1 + self.lenOfLocation) for i in range(self.lenOfVehicle)]

    def readCSV(self):
        self.adjMatrx = pd.read_csv(self.adjMxCSV, header=None).values.tolist()

        self.coordinates = pd.read_csv(self.coordCSV, header=None).values.tolist()
        self.lenOfCoord = len(self.coordinates)
        
        for i in range(self.lenOfCoord):
            tmpList = []
            for j in range(self.lenOfCoord):
                if self.adjMatrx[i][j] == 0: 
                    tmpList.append(999999)
                elif self.adjMatrx[i][j] == 2: 
                    tmpList.append(0)
                elif self.adjMatrx[i][j] == 1: 
                    dist = math.dist((self.coordinates[i][0], self.coordinates[i][1]),
                                     (self.coordinates[j][0], self.coordinates[j][1]))
                    tmpList.append(self.my_round_int(dist))
            self.locaList.append(tmpList)
        
        self.floyd(self.locaList)
        self.lenOfLocation = self.lenOfCoord - 1

        self.requestList = pd.read_csv(self.reqstCSV, header=None).values.tolist()
        self.lenOfRequest = len(self.requestList)
        
        # Data-driven Fleet Parsing
        try:
            veh_df = pd.read_csv(self.vehicleCSV)
            self.vehicleList = veh_df[['Capacity', 'CostFactor']].values.tolist()
            self.lenOfVehicle = len(self.vehicleList)
        except FileNotFoundError:
            print(f"[Error] Vehicle config '{self.vehicleCSV}' not found. Using fallback homogeneous initialization.")
            self.lenOfVehicle = self.num_vehs
            self.vehicleList = [[self.capacity, 1.0] for _ in range(self.num_vehs)]
        except KeyError as e:
            print(f"[Error] Missing expected column in '{self.vehicleCSV}': {e}")
            sys.exit(1)

    def my_round_int(self, x):
        return int((x * 2 + 1) // 2)

    def floyd(self, tmpMatrix):
        for i in range(len(tmpMatrix)):
            for j in range(len(tmpMatrix)):
                for k in range(len(tmpMatrix)):
                    tmpMatrix[j][k] = min(tmpMatrix[j][k], tmpMatrix[j][i] + tmpMatrix[i][k])

    def newVarID(self, var_type=None, *args):
        if self.registry is not None:
            if var_type is not None:
                return self.registry.get_id(var_type, *args)
            else:
                if self.vpool is None:
                    self.vpool = IDPool(start_from=self.get_vpool_start_id())
                return self.vpool.id()
        else:
            self.varID += 1
            return self.varID

    # ========================== Variable ID Generators ==========================
    
    def genXVarList(self):
        for i in range(len(self.xVarList)):
            for j in range(len(self.xVarList[i])):
                for k in range(len(self.xVarList[i][j])):
                    self.xVarList[i][j][k] = self.newVarID('x', i, j, k)

    def genYVarList(self):
        for i in range(len(self.yVarList)):
            for j in range(len(self.yVarList[i])):
                self.yVarList[i][j] = self.newVarID('y', i, j)

    def genNuVarList(self):
        for i in range(len(self.nuVarList)):
            for j in range(len(self.nuVarList[i])):
                for k in range(len(self.nuVarList[i][j])):
                    self.nuVarList[i][j][k] = self.newVarID('nu', i, j, k)

    def genUVarList(self):
        for i in range(len(self.uVarList)):
            for j in range(len(self.uVarList[i])):
                self.uVarList[i][j] = self.newVarID('u', i, j)

    def genHVarList(self):
        for i in range(len(self.hVarList)):
            for j in range(len(self.hVarList[i])):
                self.hVarList[i][j] = self.newVarID('h', i, j)

    # ========================== Variable Getters ==========================

    def getLastXVarID(self):
        return self.xVarList[-1][-1][-1]

    def getLastYVarID(self):
        if self.registry is not None:
            y_ids = [vid for key, vid in self.registry.varDict.items() if key[0] == 'y']
            return max(y_ids) if y_ids else 0
        else:
            return self.yVarList[-1][-1]

    def getLastNuVarID(self):
        return self.nuVarList[-1][-1][-1]

    def get_vpool_start_id(self):
        if self.registry is not None:
            return self.registry.get_max_core_id() + 1
        else:
            return self.varID + 1

__all__ = ["PDP_reform"]